sonar.projectKey=Anyakin666_frontend-project-46
sonar.organization=anyakin666

# Source files - только наш код
sonar.sources=src,bin

# Тесты
sonar.tests=__tests__

# Отчёты о покрытии
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Исключаем всё лишнее!
sonar.exclusions=**/node_modules/**, **/coverage/**, **/__tests__/__fixtures__/**, **/*.test.js, **/*.spec.js

# Дополнительные исключения для скрытых папок
sonar.exclusions+=,**/.git/**, **/.github/**, **/bin/gendiff.js

# Исключаем бинарные и служебные файлы
sonar.scm.exclusions.disabled=true
