sonar.projectKey=Anyakin666_frontend-project-46
sonar.organization=anyakin666

# Source files
sonar.sources=src,bin

# Tests
sonar.tests=__tests__

# Coverage reports
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclude everything except our code
sonar.exclusions=\
  **/node_modules/**,\
  **/coverage/**,\
  **/__tests__/__fixtures__/**,\
  **/*.test.js,\
  **/*.spec.js,\
  **/.*/**

# Disable SCM for excluded files
sonar.scm.exclusions.disabled=true
